[package]
name = "twimgdecode"
version = "0.1.0"
authors = ["Calvin Walton <calvin.walton@kepstin.ca>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
base64 = "0.10.1"
time = "0.1.42"
chrono = "0.4.7"
